"""Add message_id column to email

Revision ID: 0cde01d20474
Revises: 90aa56f2bd41
Create Date: 2025-08-10 17:59:30.623468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cde01d20474'
down_revision: Union[str, Sequence[str], None] = '90aa56f2bd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'message_id')
    # ### end Alembic commands ###
