"""Add received_content and generated_reply columns to email

Revision ID: 90aa56f2bd41
Revises: d1a1f0e65806
Create Date: 2025-08-10 16:01:01.137721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90aa56f2bd41'
down_revision: Union[str, Sequence[str], None] = 'd1a1f0e65806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('received_content', sa.Text(), nullable=True))
    op.add_column('email', sa.Column('generated_reply', sa.Text(), nullable=True))
    op.alter_column('email', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('email', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('email', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('email', 'generated_reply')
    op.drop_column('email', 'received_content')
    # ### end Alembic commands ###
